theme: jekyll-theme-cayman
title: Curriculum  
description: In short : lots of modeling, data wrangling and visualising, some teaching and scientific outreach, | and broad interests in other fields such as philosophy, politics, sociology, arts, geography
