theme: jekyll-theme-cayman
title: Curriculum  
description: In short: modeling, data wrangling and visualising, teaching and scientific outreach, | and broad interests in philosophy, politics, sociology
